services:
  app:
    build: ./src
    ports:
      - "8000:8000"
    secrets:
      - app_db_url
      - app_test_db_url
      - app_token_encryption
    environment:
      DATABASE_URL_FILE: /run/secrets/app_db_url
      TEST_DATABASE_URL_FILE: /run/secrets/app_test_db_url
      TOKEN_SECRET_KEY_FILE: /run/secrets/app_token_encryption
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./code
    depends_on:
      - db
  db:
    image: postgres:18
    secrets:
      - db_user
      - db_password
    container_name: fast_api_task_manager
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: task_manager
    ports:
    - "5432:5432"
    volumes:
    - data_sql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  db_test:
    image: postgres:18
    secrets:
      - test_db_user
      - test_db_password
    container_name: test_database_task_manager
    environment:
      POSTGRES_USER_FILE: /run/secrets/test_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/test_db_password
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/test_postgresql:uid=999,gid=999
volumes:
  data_sql:

secrets:
  db_user:
    environment: DATABASE_USER
  db_password:
    environment: DATABASE_PASS
  test_db_user:
    environment: TEST_DATABASE_USER
  test_db_password:
    environment: TEST_DATABASE_PASS
  app_db_url:
    environment: DATABASE_URL
  app_test_db_url:
    environment: TEST_DATABASE_URL
  app_token_encryption:
    environment: TOKEN_SECRET_KEY