[project]
name = "taskmanagementapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JaumLA", email = "joao.l.alvarez@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "psycopg2>=2.9.13",
    "pwdlib[argon2,bcrypt]>=0.3.1",
    "pyjwt>=2.14.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.42",
]

[project.scripts]
taskmanagementapi = "taskmanagementapi:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "src.taskmanagementapi.main:app"

[tool.pytest.ini_options]
# Set the default mode for handling async tests
asyncio_mode = "auto"

# Required in newer versions of pytest-asyncio to avoid warnings/errors
asyncio_default_fixture_loop_scope = "function"